# Generated by Django 4.2.5 on 2024-01-04 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/afalgugn/images')),
                ('found_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=500)),
                ('return_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/afalgugn/images')),
                ('lost_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=500)),
                ('return_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/afalgugn/images')),
                ('location', models.CharField(max_length=500)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('return_type', models.CharField(choices=[('lost', 'Lost Item'), ('found', 'Found Item')], max_length=5)),
            ],
        ),
    ]
